-- Generated by Oracle SQL Developer REST Data Services 23.1.1.345.2114
-- Exported REST Definitions from ORDS Schema Version 24.2.3.r2011847
-- Schema: BTP_XGMIS   Date: Tue Aug 06 08:32:52 CST 2024
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'BTP_XGMIS',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'btp_xgmis',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'Fuel Data',
      p_base_path      => '/fuel/',
      p_items_per_page =>  100,
      p_status         => 'PUBLISHED',
      p_comments       => 'test Rest API for Fuel data');      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'Fuel Data',
      p_pattern        => '/objects/:object/:id?',
      p_priority       => 4,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'test REST API fuel data access');


  COMMIT; 
END;